// <auto-generated />
using System;
using BiliTool.Vn.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BiliTool.Vn.Infrastructure.Migrations
{
    [DbContext(typeof(BiliToolDbContext))]
    [Migration("20260801112000_AddHisMutualTlsBinding")]
    partial class AddHisMutualTlsBinding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BiliTool.Vn.Domain.Entities.AdminAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<string>("ActorEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("actor_email");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("RemoteIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("remote_ip");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean")
                        .HasColumnName("succeeded");

                    b.Property<string>("TargetId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_type");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_admin_audit_logs_occurred_at");

                    b.HasIndex("Action", "OccurredAt")
                        .HasDatabaseName("ix_admin_audit_logs_action_occurred_at");

                    b.HasIndex("ActorId", "OccurredAt")
                        .HasDatabaseName("ix_admin_audit_logs_actor_occurred_at");

                    b.ToTable("admin_audit_logs", (string)null);
                });

            modelBuilder.Entity("BiliTool.Vn.Domain.Entities.ClinicalAuditLegalHold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("placed_at");

                    b.Property<string>("PlacedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("placed_by");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<string>("ReleasedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("released_by");

                    b.Property<string>("ResultId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("result_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ResultId", "ReleasedAt")
                        .HasDatabaseName("ix_clinical_audit_legal_holds_scope");

                    b.ToTable("clinical_audit_legal_holds", (string)null);
                });

            modelBuilder.Entity("BiliTool.Vn.Domain.Entities.ClinicalAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiClientId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("api_client_id");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EngineMode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("engine_mode");

                    b.Property<string>("EngineVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("engine_version");

                    b.Property<string>("GuidelineCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("guideline_code");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("request_json");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_json");

                    b.Property<string>("ResultId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("result_id");

                    b.Property<string>("TenantId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TraceJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("trace_json");

                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CalculatedAt")
                        .HasDatabaseName("ix_clinical_audit_logs_calculated_at");

                    b.HasIndex("GuidelineCode")
                        .HasDatabaseName("ix_clinical_audit_logs_guideline_code");

                    b.HasIndex("TenantId", "ResultId")
                        .HasDatabaseName("ix_clinical_audit_logs_tenant_result");

                    b.ToTable("clinical_audit_logs", (string)null);
                });

            modelBuilder.Entity("BiliTool.Vn.Domain.Entities.ClinicalAuditPurgeReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CutoffAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cutoff_at");

                    b.Property<int>("DeletedCount")
                        .HasColumnType("integer")
                        .HasColumnName("deleted_count");

                    b.Property<bool>("DryRun")
                        .HasColumnType("boolean")
                        .HasColumnName("dry_run");

                    b.Property<int>("EligibleCount")
                        .HasColumnType("integer")
                        .HasColumnName("eligible_count");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<int>("ProtectedByLegalHoldCount")
                        .HasColumnType("integer")
                        .HasColumnName("protected_by_legal_hold_count");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedAt")
                        .HasDatabaseName("ix_clinical_audit_purge_reports_executed_at");

                    b.ToTable("clinical_audit_purge_reports", (string)null);
                });

            modelBuilder.Entity("BiliTool.Vn.Domain.Entities.HisApiClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("ApiKeyHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("api_key_hash");

                    b.Property<string>("CertificateFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("certificate_fingerprint");

                    b.Property<string>("ClientCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("client_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("KeyFingerprint")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("key_fingerprint");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<byte[]>("PreviousApiKeyHash")
                        .HasColumnType("bytea")
                        .HasColumnName("previous_api_key_hash");

                    b.Property<DateTime?>("PreviousCertificateExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("previous_certificate_expires_at");

                    b.Property<string>("PreviousCertificateFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("previous_certificate_fingerprint");

                    b.Property<DateTime?>("PreviousKeyExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("previous_key_expires_at");

                    b.Property<string>("PreviousKeyFingerprint")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("previous_key_fingerprint");

                    b.Property<bool>("RequireMutualTls")
                        .HasColumnType("boolean")
                        .HasColumnName("require_mutual_tls");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("scopes");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("KeyFingerprint")
                        .HasDatabaseName("ix_his_api_clients_key_fingerprint");

                    b.HasIndex("PreviousKeyFingerprint")
                        .HasDatabaseName("ix_his_api_clients_previous_key_fingerprint");

                    b.HasIndex("TenantId", "ClientCode")
                        .IsUnique()
                        .HasDatabaseName("ux_his_api_clients_tenant_client_code");

                    b.ToTable("his_api_clients", (string)null);
                });

            modelBuilder.Entity("BiliTool.Vn.Domain.Entities.HisIdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("api_client_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_json");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_status_code");

                    b.Property<string>("ResultId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("result_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_his_idempotency_expires_at");

                    b.HasIndex("TenantId", "ApiClientId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_his_idempotency_client_key");

                    b.ToTable("his_idempotency_records", (string)null);
                });

            modelBuilder.Entity("BiliTool.Vn.Domain.Entities.HisOutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("api_client_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<string>("LockId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("lock_id");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<DateTime>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("ResultId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("result_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("WebhookSubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("webhook_subscription_id");

                    b.HasKey("Id");

                    b.HasIndex("ResultId")
                        .HasDatabaseName("ix_his_outbox_result_id");

                    b.HasIndex("WebhookSubscriptionId");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_his_outbox_delivery_queue");

                    b.ToTable("his_outbox_events", (string)null);
                });

            modelBuilder.Entity("BiliTool.Vn.Domain.Entities.HisTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_his_tenants_code");

                    b.ToTable("his_tenants", (string)null);
                });

            modelBuilder.Entity("BiliTool.Vn.Domain.Entities.HisWebhookSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("api_client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EndpointUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("endpoint_url");

                    b.Property<string>("EventTypes")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("event_types");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("SecretProtected")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("secret_protected");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ApiClientId", "EndpointUrl")
                        .IsUnique()
                        .HasDatabaseName("ux_his_webhook_subscription_endpoint");

                    b.ToTable("his_webhook_subscriptions", (string)null);
                });

            modelBuilder.Entity("BiliTool.Vn.Domain.Entities.HoSoBenhNhan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AnhChiBiVangDaCanChieuDen")
                        .HasColumnType("boolean");

                    b.Property<bool>("BenhTanHuyetABO")
                        .HasColumnType("boolean");

                    b.Property<bool>("BenhTanHuyetRh")
                        .HasColumnType("boolean");

                    b.Property<bool>("CoNguyCoThanKinh")
                        .HasColumnType("boolean")
                        .HasColumnName("co_nguon_co_than_kinh");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu");

                    b.Property<string>("HoTenBenhNhan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ho_ten_benh_nhan");

                    b.Property<bool>("IsTestData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_test_data");

                    b.Property<string>("MaBenhNhan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("MeBuMeHoanToan")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("NgayGioSinh")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_gio_sinh");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("NguoiDungId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("nguoi_dung_id");

                    b.Property<int>("TuoiThaiTuan")
                        .HasColumnType("integer")
                        .HasColumnName("tuoi_thai_tuan");

                    b.Property<bool>("VangDaTrong24hDau")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId")
                        .HasDatabaseName("ix_ho_so_benh_nhan_nguoi_dung_id");

                    b.HasIndex("IsTestData", "NgayTao")
                        .HasDatabaseName("ix_ho_so_benh_nhan_test_ngay_tao");

                    b.ToTable("ho_so_benh_nhan", (string)null);
                });

            modelBuilder.Entity("BiliTool.Vn.Domain.Entities.HoSoNguoiDung", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("id");

                    b.Property<string>("ChucDanh")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("chuc_danh");

                    b.Property<string>("ChuyenKhoa")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("chuyen_khoa");

                    b.Property<string>("DonViCongTac")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("don_vi_cong_tac");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("google_id");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ho_ten");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTime>("NgayDangNhapCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_sinh");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OtpCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("otp_code");

                    b.Property<DateTime?>("OtpExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("otp_expiry_time");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Salt")
                        .HasColumnType("text")
                        .HasColumnName("salt");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("so_dien_thoai");

                    b.HasKey("Id");

                    b.ToTable("ho_so_nguoi_dung", (string)null);
                });

            modelBuilder.Entity("BiliTool.Vn.Domain.Entities.LichSuTinhToan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BilirubinMgDl")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("bilirubin_mgdl");

                    b.Property<string>("ChiTietYeuCauJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CoNguyCoThanKinh")
                        .HasColumnType("boolean")
                        .HasColumnName("co_nguyen_co_than_kinh");

                    b.Property<string>("KhuyenNghiChinh")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("khuyen_nghi_chinh");

                    b.Property<string>("MucDoNguyHiem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("muc_do_nguy_hiem");

                    b.Property<DateTime>("NgayTinhToan")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tinh_toan");

                    b.Property<decimal>("NguongChieuDen")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("nguong_chieu_den");

                    b.Property<decimal>("NguongChieuDenTichCuc")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("nguong_chieu_den_tich_cuc");

                    b.Property<decimal>("NguongThayCuuMau")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("nguong_thay_cuu_mau");

                    b.Property<Guid>("PhienId")
                        .HasColumnType("uuid")
                        .HasColumnName("phien_id");

                    b.Property<int>("TuoiGio")
                        .HasColumnType("integer")
                        .HasColumnName("tuoi_gio");

                    b.Property<int>("TuoiThaiTuan")
                        .HasColumnType("integer")
                        .HasColumnName("tuoi_thai_tuan");

                    b.HasKey("Id");

                    b.HasIndex("PhienId");

                    b.ToTable("lich_su_tinh_toan", (string)null);
                });

            modelBuilder.Entity("BiliTool.Vn.Domain.Entities.MauBilirubinLuuTru", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BilirubinMgDl")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("bilirubin_mgdl");

                    b.Property<Guid>("PhienId")
                        .HasColumnType("uuid")
                        .HasColumnName("phien_id");

                    b.Property<DateTime>("ThoiGianLayMau")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("thoi_gian_lay_mau");

                    b.Property<int>("ThuTu")
                        .HasColumnType("integer")
                        .HasColumnName("thu_tu");

                    b.Property<decimal?>("TocDoThayDoi")
                        .HasPrecision(6, 3)
                        .HasColumnType("numeric(6,3)")
                        .HasColumnName("toc_do_thay_doi");

                    b.Property<int>("TuoiGioKhiLayMau")
                        .HasColumnType("integer")
                        .HasColumnName("tuoi_gio_khi_lay_mau");

                    b.HasKey("Id");

                    b.HasIndex("PhienId");

                    b.ToTable("mau_bilirubin", (string)null);
                });

            modelBuilder.Entity("BiliTool.Vn.Domain.Entities.PhienLamViec", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DiaChiIP")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("dia_chi_ip");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("NguoiDungId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("nguoi_dung_id");

                    b.Property<string>("ThietBi")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("thiet_bi");

                    b.HasKey("Id");

                    b.ToTable("phien_lam_viec", (string)null);
                });

            modelBuilder.Entity("BiliTool.Vn.Domain.Entities.XetNghiemBilirubin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BenhNhanId")
                        .HasColumnType("uuid")
                        .HasColumnName("benh_nhan_id");

                    b.Property<decimal>("BilirubinMgDl")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("bilirubin_mgdl");

                    b.Property<string>("MucDoNguyHiem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("muc_do_nguy_hiem");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<decimal?>("NguongChieuDen")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("nguong_chieu_den");

                    b.Property<decimal?>("NguongThayCuuMau")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("nguong_thay_cuu_mau");

                    b.Property<DateTime>("ThoiGianLayMau")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("thoi_gian_lay_mau");

                    b.Property<double>("TuoiGioTuDong")
                        .HasColumnType("double precision")
                        .HasColumnName("tuoi_gio_tu_dong");

                    b.HasKey("Id");

                    b.HasIndex("BenhNhanId");

                    b.ToTable("xet_nghiem_bilirubin", (string)null);
                });

            modelBuilder.Entity("BiliTool.Vn.Domain.Entities.HisApiClient", b =>
                {
                    b.HasOne("BiliTool.Vn.Domain.Entities.HisTenant", "Tenant")
                        .WithMany("ApiClients")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BiliTool.Vn.Domain.Entities.HisOutboxEvent", b =>
                {
                    b.HasOne("BiliTool.Vn.Domain.Entities.HisWebhookSubscription", "WebhookSubscription")
                        .WithMany("OutboxEvents")
                        .HasForeignKey("WebhookSubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WebhookSubscription");
                });

            modelBuilder.Entity("BiliTool.Vn.Domain.Entities.LichSuTinhToan", b =>
                {
                    b.HasOne("BiliTool.Vn.Domain.Entities.PhienLamViec", "Phien")
                        .WithMany("LichSuTinhToan")
                        .HasForeignKey("PhienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phien");
                });

            modelBuilder.Entity("BiliTool.Vn.Domain.Entities.MauBilirubinLuuTru", b =>
                {
                    b.HasOne("BiliTool.Vn.Domain.Entities.PhienLamViec", "Phien")
                        .WithMany("MauBilirubin")
                        .HasForeignKey("PhienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phien");
                });

            modelBuilder.Entity("BiliTool.Vn.Domain.Entities.XetNghiemBilirubin", b =>
                {
                    b.HasOne("BiliTool.Vn.Domain.Entities.HoSoBenhNhan", "BenhNhan")
                        .WithMany("DsXetNghiem")
                        .HasForeignKey("BenhNhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BenhNhan");
                });

            modelBuilder.Entity("BiliTool.Vn.Domain.Entities.HisTenant", b =>
                {
                    b.Navigation("ApiClients");
                });

            modelBuilder.Entity("BiliTool.Vn.Domain.Entities.HisWebhookSubscription", b =>
                {
                    b.Navigation("OutboxEvents");
                });

            modelBuilder.Entity("BiliTool.Vn.Domain.Entities.HoSoBenhNhan", b =>
                {
                    b.Navigation("DsXetNghiem");
                });

            modelBuilder.Entity("BiliTool.Vn.Domain.Entities.PhienLamViec", b =>
                {
                    b.Navigation("LichSuTinhToan");

                    b.Navigation("MauBilirubin");
                });
#pragma warning restore 612, 618
        }
    }
}
