// <auto-generated />
using System;
using BiliTool.Vn.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BiliTool.Vn.Infrastructure.Migrations
{
    [DbContext(typeof(BiliToolDbContext))]
    [Migration("20260407032814_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BiliTool.Vn.Domain.Entities.LichSuTinhToan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BilirubinMgDl")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("bilirubin_mgdl");

                    b.Property<bool>("CoNguyCoThanKinh")
                        .HasColumnType("boolean")
                        .HasColumnName("co_nguyen_co_than_kinh");

                    b.Property<string>("KhuyenNghiChinh")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("khuyen_nghi_chinh");

                    b.Property<string>("MucDoNguyHiem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("muc_do_nguy_hiem");

                    b.Property<DateTime>("NgayTinhToan")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tinh_toan");

                    b.Property<decimal>("NguongChieuDen")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("nguong_chieu_den");

                    b.Property<decimal>("NguongChieuDenTichCuc")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("nguong_chieu_den_tich_cuc");

                    b.Property<decimal>("NguongThayCuuMau")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("nguong_thay_cuu_mau");

                    b.Property<Guid>("PhienId")
                        .HasColumnType("uuid")
                        .HasColumnName("phien_id");

                    b.Property<int>("TuoiGio")
                        .HasColumnType("integer")
                        .HasColumnName("tuoi_gio");

                    b.Property<int>("TuoiThaiTuan")
                        .HasColumnType("integer")
                        .HasColumnName("tuoi_thai_tuan");

                    b.HasKey("Id");

                    b.HasIndex("PhienId");

                    b.ToTable("lich_su_tinh_toan", (string)null);
                });

            modelBuilder.Entity("BiliTool.Vn.Domain.Entities.MauBilirubinLuuTru", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BilirubinMgDl")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("bilirubin_mgdl");

                    b.Property<Guid>("PhienId")
                        .HasColumnType("uuid")
                        .HasColumnName("phien_id");

                    b.Property<DateTime>("ThoiGianLayMau")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("thoi_gian_lay_mau");

                    b.Property<int>("ThuTu")
                        .HasColumnType("integer")
                        .HasColumnName("thu_tu");

                    b.Property<decimal?>("TocDoThayDoi")
                        .HasPrecision(6, 3)
                        .HasColumnType("numeric(6,3)")
                        .HasColumnName("toc_do_thay_doi");

                    b.Property<int>("TuoiGioKhiLayMau")
                        .HasColumnType("integer")
                        .HasColumnName("tuoi_gio_khi_lay_mau");

                    b.HasKey("Id");

                    b.HasIndex("PhienId");

                    b.ToTable("mau_bilirubin", (string)null);
                });

            modelBuilder.Entity("BiliTool.Vn.Domain.Entities.PhienLamViec", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DiaChiIP")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("dia_chi_ip");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("NguoiDungId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("nguoi_dung_id");

                    b.Property<string>("ThietBi")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("thiet_bi");

                    b.HasKey("Id");

                    b.ToTable("phien_lam_viec", (string)null);
                });

            modelBuilder.Entity("BiliTool.Vn.Domain.Entities.LichSuTinhToan", b =>
                {
                    b.HasOne("BiliTool.Vn.Domain.Entities.PhienLamViec", "Phien")
                        .WithMany("LichSuTinhToan")
                        .HasForeignKey("PhienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phien");
                });

            modelBuilder.Entity("BiliTool.Vn.Domain.Entities.MauBilirubinLuuTru", b =>
                {
                    b.HasOne("BiliTool.Vn.Domain.Entities.PhienLamViec", "Phien")
                        .WithMany("MauBilirubin")
                        .HasForeignKey("PhienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phien");
                });

            modelBuilder.Entity("BiliTool.Vn.Domain.Entities.PhienLamViec", b =>
                {
                    b.Navigation("LichSuTinhToan");

                    b.Navigation("MauBilirubin");
                });
#pragma warning restore 612, 618
        }
    }
}
